### ISSUE TITLE
2 Hexagonal architecture

### ISSUE THREAD

**Issue by fabriziomoscon** [ancarebeca/port-domain-service#2]
90poe enterprise software requires us to apply specific design principles. In short these are DDD, Solid, clean code.
To practically implement those ideas we follow what some call hexagonal architecture, however if you are not familiar with it, I believe DDD can be achieved with other structure.

Please provide a PR with the changes you propose to your code to achieve separation of concerns via DDD and solid.

In spirit of sharing ideas you might find this video interesting: https://www.youtube.com/watch?v=MzTcsI6tn-0
when I was learning about this concepts, I found this repo very useful: https://github.com/tensor-programming/hex-microservice/tree/part-3

We do appreciate your efforts to improve your test.

**Comment by ancarebeca** [comment]
HI @fabriziomoscon, thank you so much for taking the time to giving me some feedback and sharing some learning resources, they are very interesting

This issue is solved as part of this [pr7](https://github.com/ancarebeca/port-domain-service/pull/7). Please, let me know your thoughts. Thanks
