### ISSUE TITLE
3 code structure must allow multiple binary

### ISSUE THREAD

**Issue by fabriziomoscon** [ancarebeca/port-domain-service#3]
Please amend the position of your main.go file to accommodate multiple binaries.
One standard practice in go is to have a `cmd` package containing as many app as we want, this could help in future if we want a `cli` for example.
Also please ensure that your main.go is minimal, to allow future cli/main.go to reuse as much code as possible.

**Comment by ancarebeca** [comment]
HI @fabriziomoscon, thank your feedback

This issue is solved as part of this https://github.com/ancarebeca/port-domain-service/pull/7. Please, let me know your thoughts. Thanks
