### ISSUE TITLE
4 Makefile

### ISSUE THREAD

**Issue by fabriziomoscon** [ancarebeca/port-domain-service#4]
Please organise create a `Makefile` which purpose is to help colleagues (without talking to you) to run all steps of the project and  work independently:

build
unit_test
run
protogen
docker?
lint?
etc

**Comment by ancarebeca** [comment]
HI @fabriziomoscon, thank your feedback

This issue is solved as part of this https://github.com/ancarebeca/port-domain-service/pull/7. Please, let me know your thoughts. Thanks
