### ISSUE TITLE
6 json streaming

### ISSUE THREAD

**Issue by theUm** [ancarebeca/port-domain-service#6]
Current approach regarding reading json is stream reading approach. Yet we do not benefiting from it. Could you make json-to-db pipe more streamlined? Now we decoding whole data at once which may cause OOM if file is big.
https://github.com/ancarebeca/port-domain-service/blob/main/internal/httpservice/ports_handler.go#L42-L44

**Comment by ancarebeca** [comment]
Hi @theUm ,  thank you for taking the time to give me feedback. 

Not sure if I understand what you are asking, please, let me clarify it with you. 
The [link](https://github.com/ancarebeca/port-domain-service/blob/main/internal/httpservice/ports_handler.go#L42-L44) that you point out is the endpoint that given a Port JSON payload it stores it in the system, this is not a file. 
It is hard to me to imagine how this object ([here](https://github.com/ancarebeca/port-domain-service/blob/a654d430f894e16b6f857f9f63400188c0a3674e/docs/postman/port-domain-services.postman_collection.json#L73) is an example) could grow in a way that could cause an OOM issue. Would you mind to provide me an example please?

There is a function responsible to load a file of Ports that is [this one](https://github.com/ancarebeca/port-domain-service/blob/a654d430f894e16b6f857f9f63400188c0a3674e/internal/reader/reader.go#L13). In that case the data is reading using a stream reading approach, as you suggested.
 
Thanks!

**Comment by theUm** [comment]
Hey, thank you for the response @ancarebeca. You right, the link is misleading, sorry bout that. [Here](https://github.com/ancarebeca/port-domain-service/blob/main/internal/reader/reader.go#L13-L40)'s the correct one.

In my opinion the file is reading in a streaming manner and thats good. But problem may happen on [this line](https://github.com/ancarebeca/port-domain-service/blob/main/internal/reader/reader.go#L39) as we collecting all the ports into single slice. 

For preventing possible OOM on very large file, the stream should go beyond this function.

Thank you for taking a part in this

**Comment by ancarebeca** [comment]
HI @theUm, thank your answer, it is clear now, I solved the issue as part of this https://github.com/ancarebeca/port-domain-service/pull/7 PR. Please, let me know if this is what you are looking for. Thanks

**Comment by theUm** [comment]
all good, thank you!
